### ISSUE TITLE
Partial failure for testGetStartDayOfCurrentWeekForSite

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-FluxC-Android#1685]
`testGetStartDayOfCurrentWeekForSite` is currently failing in both locally and in CI. This seems to be happening because the expected date is only calculated once for the local date, but the site timezone is changed several times and used for comparison.  At the time of this issue creation, the `expectedDate` points to the previous Sunday, however `dateString1` points to the next Sunday for `i=0`. I don't have enough context about whether there is a logic error in the actual code or in the tests, so I thought it'd be best to report the issue.

I suggest:
1. Adding a specific test for the case described above and verify that it consistently fails (the issue creation date can be used for it)
2. Fixing the test or the code that is being tested
3. Explaining the issue as a comment in the code (if it makes sense to do so)

@anitaa1990 Could you please look into this when you get a chance?

**Comment by anitaa1990** [comment]
Thanks for the ping @oguzkocer! I'll take a look at it this week!

**Comment by marco-altran** [comment]
I'm also having the same issue in `testGetStartDayOfCurrentWeekForSite()`, both locally and in [CI](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-FluxC-Android/2894/workflows/afd69e62-7198-4f6e-8ca7-405aadc4236b/jobs/8056)

Rolling back from 

`val expectedDate = LocalDate.now()
                .with(fieldISO, 1)
                .atStartOfDay(timezone.toZoneId())
                .toInstant()`
to
`val expectedDate = LocalDate.now()
                .with(fieldISO, 1)
                .atStartOfDay(ZoneId.systemDefault())
                .toInstant()`
does the trick but fails when it's Sunday. However I noticed that it will fail if your system default is in a region where the first day of the week is Monday. That's because the underlying code in `DateUtils.getFirstDayOfCurrentWeekBySite(site)` is not localized (it uses `Locale.ROOT` in `Calendar.getInstance(Locale.ROOT)`)

**Comment by marco-altran** [comment]
@anitaa1990 I created a PR that attempts to solve this issue. It's not the best solution possible, it's quite tricky when the expected value has to be calculated by similar code from the code your are testing, but I think it's good enough to solve this flaky test. Let me know what you think. 🤓
