### ISSUE TITLE
Test DB migration from fluxc version N to fluxc version N + 1

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-FluxC-Android#180]
Make sure we can migrate models easily from a version N to version N+1. 

We need tests to:
* Add a new field in a model.
* Remove a field.
* Rename a field.
* Change the type of a field (String to Int?).

By test, I mean manual check + some documentation.

**Comment by oguzkocer** [comment]
* Add a new field in a model

I tested [these](https://gist.github.com/oguzkocer/06b7b9ce48a73312ba58fdfdf3b37f1f) changes on `develop` which is at 324af44323c2d784ec7efad6584b31907e52194f at the time of this test. It's fairly simple to add a new property, but it took a bit of time to learn how WellSql works for me. Here is what you need to do:

1. Add the property to the model
2. Rebuild the project: This is an important step as it'll update the generated `Table` class.
3. Change the DB version in `public int getDbVersion()` of `WellSqlConfig` so it'll trigger the migration
4. Add a custom migration to `public void onUpgrade(SQLiteDatabase db, WellTableManager helper, int newVersion, int oldVersion)` in `WellSqlConfig`. We might need to use a string instead of the generated file properties for fields since the generated properties will change if you rename a property in the actual model.

Now that I got the basics of this, I am going to run more complicate scenarios. I intend to provide the example changes for those as well, so we can run them again when/if we need to. Let me know what you think @maxme!

**Comment by oguzkocer** [comment]
* Remove a field

I tested [these](https://gist.github.com/oguzkocer/6fc37718fcaba8c82613661c09ed2888) changes on `develop` which is at 324af44323c2d784ec7efad6584b31907e52194f at the time of this test. Since SQLite doesn't support removing a field, the migration needed is quite a long one. I should've picked a simpler property when I ran the test, but it worked out anyway.

My conclusion so far: WellSql doesn't affect anything for us in terms of migration. Aside from rebuilding the project after making a change to the model class, it's pretty much the same thing we do in WPAndroid.

**Comment by oguzkocer** [comment]
* Rename a field

One of the major issues with generated tables is that when you rename a property, you kind of **have to** rename the DB field as well, otherwise it'll just crash with `no such column` exception. I tested [these](https://gist.github.com/oguzkocer/0d5a8e4f2f167b70af708afd07f46929) changes on `develop` which is at 324af44323c2d784ec7efad6584b31907e52194f at the time of this test. I have spent a fair bit of time on this and still can't figure out what I am doing wrong as I am still getting an exception that says `no such column: SCREEN_NAME (code 1)` when I follow the steps I provided before. @maxme any ideas what I could be missing with this?

As a side note, I am really not sure how helpful is it to have WellSql creating the tables for us. I don't think it's a good idea to use those `createStatement` methods for example especially in migrations because it can change any time. We can maybe manually copy/paste it.

**Comment by maxme** [comment]
I'm not sure to understand the last comment about renaming a field. Should we just rename the field during  `onUpgrade()` 

Also looking at your patches, instead of creating a new table `_backup` table, copying the old to the new, dropping the old and recopying we should:

1. Rename the old table (using `ALTER TABLE AccountTable RENAME TO AccountTableBackup`)
2. Create the new table (probably using the WellSql `createStatement()`, so we're sure the newly created table is correct)
3. Do the migration, something like: `INSERT INTO AccountTable(screen_name) SELECT display_name FROM AccountTableBackup;`
4. Drop the _backup.

BTW, I have another plan for the backup and backup drop (we could keep them until version N+2, to make sure we can correct an eventual migration problem in the next version).

**Comment by oguzkocer** [comment]
Let's say, it's been a year after fluxc integration and there are 40 migrations. If we use `createStatement` methods in the table classes that's generated, we risk the chance of that method getting updated with further chances. Does that make sense? I already use the exact same string there, but I think it's better to copy paste it.

I am trying out your suggested approach now, thanks!

**Comment by oguzkocer** [comment]
I've updated the [patch](https://gist.github.com/oguzkocer/0d5a8e4f2f167b70af708afd07f46929) with your suggested approach @maxme and that didn't work at first either. It turns out you need the `db.setTransactionSuccessful();` line which fixes everything. It'd have probably worked with the previous migration as well, but this is an improvement nevertheless.

I'll run the previous migrations again with the `db.setTransactionSuccessful();` line to make sure everything is working as expected and update those patches as well.

**Comment by oguzkocer** [comment]
Just noting this here: I don't think you _have to_ rebuild the project for the changes to take effect. If you don't rebuild, you won't see the changes in the generated `Table` class, but that looks to be the only issue and the migrations work as expected. That's at least what my tests so far shown me, I might be wrong though..

**Comment by oguzkocer** [comment]
* Change the type of a field: `int` to `String`

I tested [these](https://gist.github.com/oguzkocer/63a9d0da29c58dd979629d9d5d52f2f4) changes on develop which is at 06aba04524b8fdbce9a81409d53c6614584080c6 at the time of this test. Testing `int` to `String` was the easiest with the current setup and I don't think it makes a big difference. Since there is no support for modifying column type in Sqlite, it's pretty much the same thing as renaming. I've verified the test by extracting the db and checking the column types directly.

P.S: So far my conclusion is that `WellSql` doesn't do anything for or against us when it comes to migrations. Since we write them ourselves, I don't think there is any difference with the current WPAndroid. I can keep running other tests, but at this point, I don't think we'd get surprised. What do you think @maxme?

**Comment by maxme** [comment]
> So far my conclusion is that WellSql doesn't do anything for or against us when it comes to migrations. Since we write them ourselves, I don't think there is any difference with the current WPAndroid. I can keep running other tests, but at this point, I don't think we'd get surprised. What do you think @maxme?

Thanks @oguzkocer - I think that's good enough. Just wanted to make sure the version code was used, renaming and altering were possible, etc... And that looks good so we can stop the experiment and close this ticket.
