### ISSUE TITLE
AccountStore: Implement "Magic Link" WPCom REST calls

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-FluxC-Android#199]
I think we only need to call these 2 endpoints:
- `/is-available/email`
- `/auth/send-login-email`

More here: https://github.com/wordpress-mobile/WordPress-Android/blob/edd7185c51e2cd60a5e8e6f53fd8e6b0d0f1f978/libs/networking/WordPressNetworking/src/main/java/org/wordpress/android/networking/RestClientUtils.java#L293-L300

**Comment by aforcier** [comment]
👍 We may as well add the rest of the `is-available` endpoints while we're at it - or at least `is-available/username`, which we're very likely to use in the near future. There's also `is-available/blog` and `is-available/domain`.

Interestingly, these endpoints aren't part of the normal REST structure (they're under `https://public-api.wordpress.com/` rather than `https://public-api.wordpress.com/rest/vX/`), so we'll need to make some modifications to [`WPComEndpoint`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/06aba04524b8fdbce9a81409d53c6614584080c6/fluxc-annotations/src/main/java/org/wordpress/android/fluxc/annotations/endpoint/WPComEndpoint.java). It might even be better to add them as a separate endpoint class entirely.

**Comment by aforcier** [comment]
Added in #220.
