### ISSUE TITLE
Sort `ListItemModel` by its `RemoteOrderId`

### ISSUE THREAD

**Issue by wzieba** [wordpress-mobile/WordPress-FluxC-Android#2007]
This description applies to `WCAndroid` use case. I don't know how things work in `WPAndroid`, I'd appreciate feedback on this 🙌 .

**Context**
When we receive `orderSummaries` in `OrderRestClient#fetchOrderListSummaries`, [we put them into database.](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/33dda8e285be363a21886a68ecd084456a8a6bca/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderRestClient.kt#L138) Orders received from backend are sorted **descendantly**. When we put them into database, SQLite assigns id's **ascendantly** for every next summary. So we end up with such data:

<img width="536" alt="Screenshot 2021-05-24 at 15 57 29" src="https://user-images.githubusercontent.com/5845095/119358453-ef490600-bca8-11eb-9b1f-9b26ea4f8e12.png">

Currently we get `ListItem`s from db by [sorting them **ascendantly** by their generated `_id`.](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/5f2fb2f652ec711d17c5b7392c54491b1259f370/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/ListItemSqlUtils.kt#L42) so we end up with list sorted **ascendantly** by `REMOTE_ITEM_ID`.

**What's wrong with implementation**
In case, when we want to insert a single, new `ListItemModel` we would have to look for the smallest `_id` value, and subtract 1 from it. It's possible but seems over-complicated and hacky.

**Solution**
Eventually, I think we want to have list sorted by `REMOTE_ITEM_ID` so maybe it's ok to just get `ListItemModel` sorted by it.

Part of https://github.com/woocommerce/woocommerce-android/issues/4053

**Comment by oguzkocer** [comment]
@wzieba `ListStore` and its components are specifically designed to discourage this kind of intervention. Instead, refreshing the whole list made to be a cheap operation by only fetching ids of the items and only updating/fetching items if it's necessary. In the case of https://github.com/woocommerce/woocommerce-android/issues/4053, what you probably want to do is ask the list to be refreshed.

I've worked on a set of documentation for ListStore which I unfortunately never got around to finish, but it should still give you some context into why it's designed the way it's and how to get certain workflows working: https://github.com/wordpress-mobile/WordPress-FluxC-Android/wiki/ListStore-Guide:-Introduction-(WIP)

Please let me know if I can help further clarify anything or help you implement that issue. Also, you can probably ping @AmandaRiu for WCAndroid implementation specific questions.

**Comment by wzieba** [comment]
@oguzkocer thank you for your input, it's very appreciated as I'm discovering the whole `ListStore` idea and concept behind it. Linked documentation, even if not complete, will be for sure helpful.

> what you probably want to do is ask the list to be refreshed.

Unfortunately, this is what I try to optimize. In case of slow hosting provider it takes 5-7 seconds to only get a response from remote about which orders we want to update. Then again we have to wait few seconds for full rich-orders to be fetched. This gives us something about ~10 seconds of waiting.

When receiving a notification we already know which exactly order we should fetch so we don't have this first request about which orders should we get. Also, this will reduce number of calls which is nice in terms of performance optimization.

I'm okay with leaving `ListItemModel` untouched and also don't touch the rest of the "core" of it but on the other hand - I don't understand a reason for sorting it in an order of inserting it (which is a reverse-order of creating them IRL).

I thought it's a bug in implementation as in [PR which introduced](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/890) I haven't spotted any reason for this idea and the [sorting parameter is from different table](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/5f2fb2f652ec711d17c5b7392c54491b1259f370/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/ListItemSqlUtils.kt#L42) which also suggested me that it's not an intended way.

**Comment by oguzkocer** [comment]
> Unfortunately, this is what I try to optimize. In case of slow hosting provider it takes 5-7 seconds to only get a response from remote about which orders we want to update. Then again we have to wait few seconds for full rich-orders to be fetched. This gives us something about ~10 seconds of waiting.

With Jetpack, we should be hitting WordPress servers, right? It's interesting that it's taking this long. When this was first ported to WCAndroid, I remember there was an issue with just fetching order ids not working as intended and the server would treat it as if it's the whole item. Is this maybe related to that? I assumed it'd be fixed/improved by now, but maybe it's not?

> I'm okay with leaving ListItemModel untouched and also don't touch the rest of the "core" of it but on the other hand - I don't understand a reason for sorting it in an order of inserting it (which is a reverse-order of creating them IRL).

That is because we let server sort the items for us, so the insertion order is always the correct one. Here is for example how posts are ordered: https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostRestClient.java#L741-L746

Item-list is a many to many relationship. The same item can be in several lists and the same item in each list can be in a different place. That's why the remote item id, in terms of sorting it, is meaningless.

Does that make sense? I am happy to walk you through some of the `ListStore` mechanics and how we can maybe address the issue you're having through a call. One thing to keep in mind though is that some of the ideas/assumptions are core to its design and it's certainly not a solution that fits every case. It has very specific and deliberate trade-offs which works well when we can control the API, but can fall short otherwise.

> I thought it's a bug in implementation as in PR which introduced I haven't spotted any reason for this idea and the sorting parameter is from different table which also suggested me that it's not an intended way.

It's definitely intended.

**Comment by wzieba** [comment]
> With Jetpack, we should be hitting WordPress servers, right? It's interesting that it's taking this long.

True, we target WordPress servers but, if I'm not mistaken, somehow we have to get data from the database stored on private hosting provider. I don't know architecture of the WooCommerce yet so please take it we a grain of salt. 

Anyway, we end up with long waiting time, here are some measurements:

### "Fast" hosting provider (Pressable) 1692ms

##### Fetching ids:
<img width="2264" alt="Screenshot 2021-05-25 at 11 36 23" src="https://user-images.githubusercontent.com/5845095/119476434-58cf2000-bd4e-11eb-95e9-5e02dd2c79f8.png">


##### Fetching orders:
<img width="2258" alt="Screenshot 2021-05-25 at 11 37 00" src="https://user-images.githubusercontent.com/5845095/119476060-fe35c400-bd4d-11eb-9a9c-9835f962f759.png">

☝️ those looks acceptable I think. But

### "Slow" hosting provider (Aruba.it) 11 000ms

##### Fetching ids:
<img width="2256" alt="Screenshot 2021-05-25 at 11 28 24" src="https://user-images.githubusercontent.com/5845095/119476261-2fae8f80-bd4e-11eb-813d-4ea299aaa789.png">

##### Fetching orders:
<img width="2243" alt="Screenshot 2021-05-25 at 11 27 49" src="https://user-images.githubusercontent.com/5845095/119476315-3c32e800-bd4e-11eb-96f6-7b7d73006b31.png">

And this is a problem.

By presenting this I just want to raise awareness that maybe it'd be a good idea to add an API for diff mechanism for a consumer to fetch a single order/post - this might be useful in discussed notifications case but also e.g. when navigating back to the list of orders after editing one. WDYT?

---

> I am happy to walk you through some of the `ListStore` mechanics and how we can maybe address the issue you're having through a call.

Thank you very much, as soon as I'll stumble upon some question after reading the docs, I'll ping you for a possibility of call.

> One thing to keep in mind though is that some of the ideas/assumptions are core to its design and it's certainly not a solution that fits every case. It has very specific and deliberate trade-offs which works well when we can control the API, but can fall short otherwise.

Gotcha, generally I love the idea and its execution. I'm sure it highly benefits overall user experience and performance of the app. This is problematic only in cases when we exactly know what we want to update or fetch and, while having a slow hosting provider, we probably don't want to perform any not completely necessary communication with backend.

---

To wrap up - I think it might be a good idea to add an API for fetching a single order/post/item in cases where performance is a key. After learning more about `ListStore` I'll be happy to suggest some non-breaking API addition to `ListStore`. Does it sound good to you @oguzkocer @AmandaRiu ?

**Comment by oguzkocer** [comment]
> By presenting this I just want to raise awareness that maybe it'd be a good idea to add an API for diff mechanism for a consumer to fetch a single order/post - this might be useful in discussed notifications case but also e.g. when navigating back to the list of orders after editing one. WDYT?

I don't think this is possible without a new endpoint that can tell us where to put the item in a list. You'll also need to put it in every list the item exists in.

> when navigating back to the list of orders after editing one

This shouldn't require a refresh because the `ListStore` does not own or care about actual items. If an item is updated in the DB, it should be reflected in every list without any further action. One exception to that is the summary items, and these are handled separately by each feature. In post list, we don't need to update the summaries because iirc it doesn't contain any editable data, but if in order list it does, it'll need to be updated alongside the actual items. In either case, this does not require a network action.

> Gotcha, generally I love the idea and its execution. I'm sure it highly benefits overall user experience and performance of the app. This is problematic only in cases when we exactly know what we want to update or fetch and, while having a slow hosting provider, we probably don't want to perform any not completely necessary communication with backend.

If the server is not optimized to send some fields any faster than full items, `ListStore` is not a good fit and alternatives should be considered. Here is how fast this is for posts endpoint using our division p2:

![post fields request](https://user-images.githubusercontent.com/662023/119701822-c9477100-be22-11eb-8cfc-5d0cd1d18a91.png)

---

> After learning more about `ListStore` I'll be happy to suggest some non-breaking API addition to `ListStore`. 

Sounds great - what you are looking to do may not be possible in a reasonable way, but I am happy to discuss it further to see if we can find one.

**Comment by AmandaRiu** [comment]
@wzieba Looking at everything you've presented (thank you for all the details and thank you @oguzkocer for providing so much context), I'd say one optimization that could be made would be to try a lower `per_page` value. Looking at the screenshots provided it looks to be currently set at 60, but since only about +/- 6 orders are visible in the Orders List view at a time, this number could be cut down to a smaller value to maybe speed things up. As far as the original reason for this issue, I'm not sure I understand how the order of records in the database effects any of this though so I'm a bit confused as to why changing this order would effect how fast orders are fetched or even why it would speed anything up. 

> To wrap up - I think it might be a good idea to add an API for fetching a single order/post/item in cases where performance is a key. After learning more about ListStore I'll be happy to suggest some non-breaking API addition to ListStore. Does it sound good to you @oguzkocer @AmandaRiu ?

I'd be open to that definitely. 👍

**Comment by wzieba** [comment]
> I don't think this is possible without a new endpoint that can tell us where to put the item in a list. You'll also need to put it in every list the item exists in.

This might be the case for `WCAndroid` only, but when we receive a single order we know it's state and we only have two lists in the app - `processing` and `all orders` so I think we could assign an order to the correct list, or am I missing something?

> This shouldn't require a refresh because the ListStore does not own or care about actual items. 

Thanks, this is nice and it works as you explain - editing a field from `Order` directly in SQL and just invalidating a list presents a new result. We probably mistakenly do a refresh after every change to orders, but I'll have to double check that.

> but if in order list it does

Like in WP, `WCOrderSummaryModel` does not contain any editable data so that's good.

> If the server is not optimized to send some fields any faster than full items, `ListStore` is not a good fit and alternatives should be considered.

I didn't mean that server is not optimized that less-fields request won't be faster but either way it'll take some time. For slow hosting providers, _any_ query takes noticeable amount of it. This is why I'm looking everywhere to reduce any additional calls.

> Sounds great - what you are looking to do may not be possible in a reasonable way, but I am happy to discuss it further to see if we can find one.

Thank you! I have to reevaluate a "effort/value" calculus - I didn't know how complex change it will be.

---

Thank you @AmandaRiu for stepping here, I appreciate it 🙌 .

> I'd say one optimization that could be made would be to try a lower `per_page` value.

Good observation - I'll check how times of the request change with lower `per_page` value, especially on slow hosting providers.

> As far as the original reason for this issue, I'm not sure I understand how the order of records in the database effects any of this though so I'm a bit confused as to why changing this order would effect how fast orders are fetched or even why it would speed anything up.

Yeah, that's a little shadowed by the whole discussion but initially this change was meant to be one of a few issues/PRs which meant to add a possibility to fetch a single order while creating a summary for it so when receiving a notification about new  order, client wouldn't have to call a backend with a request for ids of orders to fetch (because it's already known).

**Comment by oguzkocer** [comment]
> This might be the case for WCAndroid only, but when we receive a single order we know it's state and we only have two lists in the app - processing and all orders so I think we could assign an order to the correct list, or am I missing something?

@wzieba I am sorry, I don't think I understand what you mean here.

Fwiw, (unless I am missing something) there is a _very_ hacky way to get this done without touching `ListStore` at all and I am happy to share that if it becomes a necessity. It's not something I wanted to volunteer because these hacks can be more harmful then helpful.

**Comment by wzieba** [comment]
Just to make sure - I'm not looking/planning to develop some hacks or quick-term solution - I hope that this discussion will help me to understand any challenges that you think might raise when adding this feature (fetching a single order so it works with diff mechanism and shows on a list). I just want to understand your concerns with how this should work.

Breaking this into more step-by-step list of what I imagine fetching a single order can look like this:
1. Request an order from a remote
2. Save order to the local persistence
3. Create `WCOrderSummaryModel` of the order, save it to local persistence
4. Create `ListItemModel` based on summary or order. Determine its `LIST_ID` - e.g. if it's `processing`, use `processing` list id. This is what I meant when writing 

> when we receive a single order we know its state and we only have two lists in the app - processing and all orders so I think we could assign an order to the correct list.

5. We end up with updated full dataset without need to fetch for the diff from remote.

Does it make sense? Does the point 4 seems hacky?

**Comment by oguzkocer** [comment]
>  Does the point 4 seems hacky?

Yes it does, because features shouldn't be aware of the internals of `ListStore` components. There is also a better(?) hack, I'll explain it below.

> We end up with updated full dataset without need to fetch for the diff from remote.

We do, but it's not ordered. There is nothing in `ListStore` that knows about how a list is ordered, so there is no way to know where an item should be inserted. We can't track that in `ListStore` (easily), because it's a generic component which doesn't know about things like `date` etc.

---

The way you can do this is to query the summary models, which should match the items in `ListStore`, add the item in its correct place and then tell `ListStore` that you've fetched the first page of a list which will override the full list. If you do this for each list type, you'd have manually inserted the item. [Here is how you can tell `ListStore` how you fetched the order list.](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCOrderStore.kt#L584-L593)

_P.S:_ It pains me to explain this hack, but I've grown to understand that things are not always in our control so we may not be able to do the "right" thing at times. If it's between this hack and losing the users extra bunch of seconds, I think the hack is OK. What I'll suggest, if you do follow this route, is to try to contain this as much as possible and be verbose in method naming & documentation so it's clear what's going on. That way we can limit its potential damage in the long run.

**Comment by wzieba** [comment]
> We do, but it's not ordered.

Gotcha, I've missed this fact.

> The way you can do this is to query the summary models, which should match the items in ListStore, add the item in its correct place and then tell ListStore that you've fetched the first page of a list which will override the full list.

Thanks for the explanation. True, this way we have a correct order of the items.

> It pains me to explain this hack, but I've grown to understand that things are not always in our control so we may not be able to do the "right" thing at times. If it's between this hack and losing the users extra bunch of seconds, I think the hack is OK.

I understand that it's kind of a breach into how it was designed. I feel you that the fix, even it'll work properly, might be a potential dangerous precedence. I'm not sure how big priority fetching a single order is in scope of performance improvements though. As I mentioned, I'll have to re-check other priorities and effort/value calculus and with every new thing I learn, the "effort" part grows 🥲.

> What I'll suggest, if you do follow this route, is to try to contain this as much as possible and be verbose in method naming & documentation so it's clear what's going on. That way we can limit its potential damage in the long run.

Sure, good suggestions, thanks 🙌
